version: 2
executorType: docker

jobs:
  build:
    working_directory: ~/deploy
    docker:
      - image: docker:17
    steps:
      - checkout

      - type: setup-docker-engine

      - run:
          name: Build Node Docker image
          command: echo "Build docker image"

      - run:
          name: Build Flutter Docker image
          command: echo "Build flutter image"
      - run:
          name: "Upload docker images"
          command: echo "Upload docker images"
