version: 2.1

jobs:
  build:
    working_directory: ~/deploy
    docker:
      - image: docker:17

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Node Docker image
          command: docker build -t hugoai/node:latest ./node

      - run:
          name: Build Flutter Docker image
          command: docker build -t hugoai/flutter:latest ./flutter

      - when:
          condition:
            and:
              - equal: [ master, << pipeline.git.branch >> ]

          steps:
            - run:
                name: "Upload docker images"
                command: |
                  docker login -u engineeringhugoai -p $DOCKER_HUB_PASSWORD
                  docker push hugoai/node:latest
                  docker push hugoai/flutter:latest

workflows:
  build_and_upload:
    jobs:
      - build
